function line(parts) {
  return parts.filter(Boolean).join('');
}

export function buildPlanMarkdown({ finalPlan, clarified, idea }) {
  if (!finalPlan) {
    return '';
  }

  const title = finalPlan.title || clarified?.summary || 'Execution plan';
  const lines = [`# ${title}`, ''];

  if (finalPlan.overview || finalPlan.summary) {
    lines.push(finalPlan.overview || finalPlan.summary, '');
  }

  if (idea) {
    lines.push('> **Original idea:** ' + idea, '');
  }

  if (finalPlan.timeline?.totalDuration) {
    lines.push(`**Timeline:** ${finalPlan.timeline.totalDuration}`, '');
  }

  if (finalPlan.selectedPath?.title) {
    lines.push(`**Chosen path:** ${finalPlan.selectedPath.title}`, '');
  }

  if (finalPlan.firstAction) {
    lines.push('## First action', finalPlan.firstAction, '');
  }

  if (finalPlan.roadmap?.length) {
    lines.push('## Roadmap', '');
    finalPlan.roadmap.forEach((step, index) => {
      lines.push(line([`### ${step.order || index + 1}. ${step.title}`]));
      if (step.timeframe) {
        lines.push(`*${step.timeframe}*`);
      }
      if (step.description) {
        lines.push('', step.description);
      }
      if (step.tasks?.length) {
        lines.push('');
        step.tasks.forEach((task) => lines.push(`- [ ] ${task}`));
      }
      if (step.milestone) {
        lines.push('', `**Milestone:** ${step.milestone}`);
      }
      lines.push('');
    });
  }

  if (finalPlan.risks?.length) {
    lines.push('## Risks & mitigations', '');
    finalPlan.risks.forEach((risk) => {
      lines.push(`- **${risk.title}** (${risk.severity || 'medium'}): ${risk.description || ''}`);
      if (risk.mitigation) {
        lines.push(`  - *Mitigation:* ${risk.mitigation}`);
      }
    });
    lines.push('');
  }

  if (finalPlan.confidenceNote) {
    lines.push('---', '', `_${finalPlan.confidenceNote}_`, '');
  }

  lines.push('---', '', '_Generated by ForgeFlow — decision support, not advice._');

  return lines.join('\n');
}

export function downloadPlanMarkdown({ finalPlan, clarified, idea }) {
  const markdown = buildPlanMarkdown({ finalPlan, clarified, idea });
  if (!markdown) {
    return;
  }

  const slug = (finalPlan.title || clarified?.summary || 'forgeflow-plan')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 50) || 'forgeflow-plan';

  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${slug}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
